# Generated by Django 5.0.7 on 2024-11-24 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
