# Generated by Django 5.0.7 on 2025-01-07 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='uploaded_at',
        ),
    ]
