# Generated by Django 5.0.7 on 2024-11-24 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examapi', '0002_rename_user_customuser'),
    ]

    operations = [
        migrations.
        AlterModelTable(
            name='customuser',
            table='customuser',
        ),
    ]
