# Generated by Django 5.0.7 on 2025-01-07 14:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapi', '0002_remove_uploadedfile_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
