# Generated by Django 5.0.7 on 2024-11-30 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examapi', '0003_alter_customuser_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
