# Generated by Django 5.1.3 on 2024-12-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapi', '0009_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
