# Generated by Django 5.1.3 on 2024-12-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapi', '0011_examresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='exam_name',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='score',
        ),
        migrations.AddField(
            model_name='examresult',
            name='score_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='wrong_answers',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='correct_answers',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='total_questions',
            field=models.IntegerField(null=True),
        ),
    ]
