# Generated by Django 5.1.4 on 2024-12-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapi', '0014_remove_examresult_deadline_examresult_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
