# Generated by Django 5.1.4 on 2024-12-29 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examapi', '0015_alter_examresult_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='uploaded_at',
        ),
    ]
