# Generated by Django 5.1.4 on 2024-12-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapi', '0017_examresult_date_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='date_at',
        ),
        migrations.AddField(
            model_name='examresult',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
